### ISSUE TITLE
Server Config appears to apply config settings to servers you have already joined

### ISSUE THREAD

**Issue by thedoctorjtd** [Ekibunnel/BetterDiscordAddons#3]
I haven't been able to pinpoint the exact trigger, however I know that this does not happen when Server Config is disabled - periodically all servers, even ones that I have joined years ago and placed manual settings on, will be overridden by Server Config leading me to wonder why I'm no longer getting any notifications.

**Comment by Ekibunnel** [comment]
Never noticed/had this issue, I have some manual settings on some servers since day one of this addons being made and they still are applied.

config are only applied when [GUILD_CREATE is trigger](https://github.com/Ekibunnel/BetterDiscordAddons/blob/7451624d7d81c1d681a378090783f262b37f1a32/Plugins/ServerConfig/src/index.js#L42C38-L42C50) and that should be fired only when the client join a guild.

So for something to fire GUILD_CREATE on all your servers either you have some other addons making change to servers and triggering GUILD_CREATE by doing so or you are using a feature I don't use that """reload""" all servers.

maybe the "Switch Account" feature could cause this, are you using that feature ?
I don't have another discord account to test this.

I'm gona take a look at this later today.

**Comment by Ekibunnel** [comment]
I could not replicate, weird.

Pushed 1.0.5 https://github.com/Ekibunnel/BetterDiscordAddons/commit/76325617981b053640fcdafb013046ea2fc073a6 .

It prevent from applying the config on a server that has been joined more than a minute ago, this should solve your issue.
